
service: learn-sls
# app and org for use with dashboard.serverless.com
app: learn-sls
org: dctri211997

provider:
  name: aws
  runtime: nodejs12.x

functions:
  test:
    handler: handler.test
    events:
      - http:
          path: api/test
          method: GET
  auth:
    handler: auth.authorize
  hello:
    handler: handler.hello
    events:
      - http:
          path: api/hello
          method: GET
          authorizer: auth
