
service: learn-sls
# app and org for use with dashboard.serverless.com
app: learn-sls
org: dctri211997

provider:
  name: aws
  runtime: nodejs12.x

functions:
  register:
    handler: handler.register
    events:
      - http:
          path: api/register
          method: POST
  verifyAccount:
    handler: handler.verifyAccount
    events:
      - http:
          path: api/verifyAccount
          method: POST
  session:
    handler: handler.login
    events:
      - http:
          path: api/session
          method: POST
  auth:
    handler: auth.authorize
  hello:
    handler: handler.hello
    events:
      - http:
          path: api/hello
          method: GET
          authorizer: auth
